Repository openshift-knative/serving, pull requests merged in 2022-11, with the labels that each got.

#2 Revert "Deprecate openshift/knative-serving (#1278)"
  README.md
Labels: approved, lgtm

#3 Use openshift-knative org in udpate-to-head.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#6 [RELEASE-1.6] Reset drainer to avoid deadlock when liveness probe fails
  cmd/queue/main.go
  test/test_images/readiness/service.yaml
  vendor/knative.dev/pkg/network/handlers/drain.go
Labels: approved, lgtm

#8 [RELEASE-v1.8] Revert "upgrade k8s autoscaling to v2
  config/core/deployments/activator-hpa.yaml
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/hpa/hpa.go
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/autoscaling/hpa/resources/hpa.go
  pkg/reconciler/autoscaling/hpa/resources/hpa_test.go
  pkg/reconciler/testing/v1/listers.go
  test/e2e/autoscale_hpa_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/autoscaling/v2beta2/horizontalpodautoscaler/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/autoscaling/v2beta2/horizontalpodautoscaler/horizontalpodautoscaler.go
  vendor/modules.txt
Labels: approved, lgtm

#7 [RELEASE-1.6] Enable secret informer filtering
  openshift/patches/007-secret-informer.patch
  test/e2e/domainmapping/domain_mapping_test.go
  third_party/kourier-latest/kourier.yaml
Labels: approved, lgtm

#9 [RELEASE-v1.6][BACKPORT] Allow setting seccompProfile to enable using restricted security profile
  config/core/configmaps/features.yaml
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
Labels: approved, lgtm

#12 [RELEASE-v1.6] [BACKPORT] Fix sc for psp compliance
  config/core/deployments/activator.yaml
  config/core/deployments/autoscaler.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/domainmapping-controller.yaml
  config/core/deployments/domainmapping-webhook.yaml
  config/core/deployments/webhook.yaml
  config/hpa-autoscaling/controller.yaml
  config/post-install/default-domain.yaml
  config/post-install/storage-version-migration.yaml
  openshift/release/artifacts/2-serving-core.yaml
  openshift/release/download_release_artifacts.sh
  openshift/release/knative-serving-ci.yaml
  openshift/release/knative-serving-knative-v1.6.0.yaml
  openshift/release/manifest-patches/005-psp.patch
  third_party/cert-manager-latest/cert-manager.yaml
  third_party/cert-manager-latest/net-certmanager.yaml
  third_party/contour-latest/contour.yaml
  third_party/contour-latest/net-contour.yaml
  third_party/gateway-api-latest/net-gateway-api.yaml
Labels: approved, lgtm

#16 Force PR title for sync job
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#13 [RELEASE-v1.6] [BACKPORT] Run queue proxy with restricted profile
  pkg/reconciler/revision/resources/queue.go
Labels: approved, lgtm

#18 [RELEASE-1.6] Feature: Let users set `allowPrivilegeEscalation = false` on ksvc.
  config/core/300-resources/configuration.yaml
  config/core/300-resources/revision.yaml
  config/core/300-resources/service.yaml
  hack/schemapatch-config.yaml
  openshift/release/artifacts/1-serving-crds.yaml
  openshift/release/artifacts/2-serving-core.yaml
  openshift/release/download_release_artifacts.sh
  openshift/release/knative-serving-ci.yaml
  openshift/release/knative-serving-knative-v1.6.0.yaml
  openshift/release/manifest-patches/005-psp.patch
  pkg/apis/serving/fieldmask.go
  pkg/apis/serving/fieldmask_test.go
Labels: approved, lgtm

#20 Fix minimum version patch
  openshift/patches/005-k8s-min.patch
Labels: approved, lgtm

#21 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#23 [release-v1.5] SRVKS-981 Multiarch test images
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
  .github/workflows/knative-vulnerability.yaml
  .github/workflows/multiarch-build.yaml
  .ko.yaml
  Makefile
Labels: approved, lgtm

#24 [main] SRVKS-981 Multiarch test images
  .github/workflows/multiarch-build.yaml
  Makefile
  openshift/release/create-release-branch.sh
Labels: approved, lgtm

#28 [release-v1.6] SRVKS-981 Multiarch test images
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
  .github/workflows/knative-vulnerability.yaml
  .github/workflows/multiarch-build.yaml
  .ko.yaml
  Makefile
Labels: approved, lgtm

#30 [release-v1.8] SRVKS-981 Multiarch test images
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
  .github/workflows/knative-vulnerability.yaml
  .github/workflows/multiarch-build.yaml
  Makefile
Labels: approved, lgtm

#31 [RELEASE-v1.8] Drop SeccompProfile from deployment
  openshift/patches/008-remove-seccomp-queue.patch
  pkg/reconciler/revision/resources/queue.go
Labels: approved, lgtm

#34 [MAIN] Upgrade to v1beta1
  openshift/e2e-common.sh
Labels: approved, lgtm

#40 [MAIN] Remove seccompProfile patch for queue proxy
  openshift/patches/008-remove-seccomp-queue.patch
Labels: approved, lgtm

#45 Remove upstream workflows from nightly sync
  openshift/release/update-to-head.sh
Labels: do-not-merge/hold, approved, lgtm

#46 [RELEASE-v1.5] Ensure probes from the autoscaler are not passed to the user-container (#13506)
  cmd/queue/main.go
  openshift/e2e-common.sh
  test/e2e/autoscale_test.go
Labels: approved, lgtm

#49 [RELEASE-v1.7] Ensure probes from the autoscaler are not passed to the user-container (#13504)
  pkg/queue/sharedmain/main.go
  test/e2e/autoscale_test.go
Labels: approved, lgtm
