Repository openshift-knative/serving, pull requests merged in 2023-04, with the labels that each got.

#248 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
  openshift/ci-operator/build-image/Dockerfile
Labels: kind/sync-fork-to-upstream

#258 Revert to golang 1.18
  openshift/ci-operator/build-image/Dockerfile
Labels: approved

#261 [RELEASE-1.8] wait for config-map changes to be propagated for builds to work on golang 1.19
  openshift/e2e-common.sh
Labels: approved, lgtm

#266 [RELEASE-1.9] Fix cm configuration and checks
  openshift/e2e-common.sh
Labels: approved, lgtm

#275 [release-1.8] cherry pick fixes (#13836)
  cmd/default-domain/main.go
  pkg/autoscaler/statserver/server.go
  pkg/queue/sharedmain/handlers.go
  pkg/queue/sharedmain/main.go
  pkg/queue/sharedmain/servers.go
Labels: approved, lgtm

#274 [release-1.9] cherry pick fixes (#13829)
  cmd/default-domain/main.go
  pkg/autoscaler/statserver/server.go
  pkg/queue/sharedmain/handlers.go
  pkg/queue/sharedmain/main.go
  pkg/queue/sharedmain/servers.go
Labels: approved, lgtm

#277 [RELEASE-1.7] Trigger CI to get images with new tag schema
  CI
Labels: approved, lgtm

#278 [RELEASE-1.8] Trigger CI to get images with new tag schema
  ci
Labels: approved, lgtm

#279 [RELEASE-1.9] Trigger CI to get images with new tag schema
  ci
Labels: approved, lgtm

#283 [RELEASE-1.7] Trigger CI to get images with old tag schema
  CI
Labels: approved, lgtm

#286 Remove CI generation scripts and update documentation
  Makefile
  README.md
  RELEASE.md
  openshift/ci-operator/generate-ci-config.sh
  openshift/ci-operator/update-ci.sh
Labels: approved, lgtm

#296 [RELEASE-1.9] [SRVKS-1046] Deployment probe fixes
  cmd/domain-mapping-webhook/main.go
  cmd/webhook/main.go
  config/core/deployments/controller.yaml
  config/core/deployments/domainmapping-controller.yaml
  openshift/release/artifacts/serving-core.yaml
Labels: approved, lgtm

#295 [RELEASE-1.8] Run `openshift/release/generate-release.sh 1.8.5`
  openshift/release/artifacts/serving-core.yaml
Labels: approved, lgtm
