Repository openshift-knative/serving, pull requests merged in 2023-06, with the labels that each got.

#334 Validate GH action only on PR
  .github/workflows/validate.yaml
Labels: approved, lgtm

#341 [SRVKS-1071] Add github action to sync upstream
  .github/workflows/sync-upstream.yaml
Labels: approved, lgtm

#343 [SRVKS-1071] Add github action to sync upstream
  .github/workflows/sync-upstream.yaml
Labels: approved, lgtm

#344 Add github user name
  .github/workflows/sync-upstream.yaml
Labels: approved

#346 Update docs about how to sync
  README.md
Labels: approved, lgtm

#349 [RELEASE-1.9] Sync upstream release
  config/core/deployments/activator.yaml
  config/core/deployments/autoscaler.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/domainmapping-controller.yaml
  config/core/deployments/domainmapping-webhook.yaml
  config/core/deployments/webhook.yaml
  config/hpa-autoscaling/controller.yaml
  openshift/release/artifacts/serving-core.yaml
  openshift/release/artifacts/serving-hpa.yaml
  pkg/activator/net/lb_policy.go
  pkg/activator/net/lb_policy_test.go
Labels: approved, lgtm

#352 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#356 Remove podspec-volumes-emptydir toggle
  openshift/e2e-common.sh
Labels: approved, lgtm

#357 [RELEASE-v1.10] Add common option for e2e tests
  openshift/e2e-common.sh
Labels: approved, lgtm

#361 Add common option for e2e tests
  openshift/e2e-common.sh
Labels: approved, lgtm
