Repository openshift-knative/serving, pull requests merged in 2024-12, with the labels that each got.

#1036 [main] Remove multiarch build action
  .github/workflows/multiarch-build.yaml
Labels: approved, lgtm

#995 [RELEASE-1.16] Remove min-available patch as its now handled in S-O
  config/core/deployments/activator-hpa.yaml
  config/core/deployments/webhook-hpa.yaml
  openshift/patches/005-pdb-minavailable.patch
  openshift/release/artifacts/serving-core.yaml
Labels: approved, lgtm, ok-to-test

#1047 :robot: Triggering CI on branch 'release-next' after syncing to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1048 :robot: Triggering CI on branch 'release-next' after syncing to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1046 Remove min-available patch as its now handled in S-O
  openshift/patches/005-pdb-minavailable.patch
Labels: approved, lgtm

#1056 [RELEASE-v1.15] Fix configuration metadata inconsistency (#15601)
  pkg/reconciler/labeler/accessors.go
  pkg/reconciler/service/resources/configuration.go
Labels: approved, lgtm

#1059 [RELEASE-v1.16] Update golang.org/x/crypto to 0.31.0
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_noasm.go
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64x.go
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64x.s
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.s
  vendor/golang.org/x/sys/cpu/asm_darwin_x86_gc.s
  vendor/golang.org/x/sys/cpu/cpu_darwin_x86.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.s
  vendor/golang.org/x/sys/cpu/cpu_gccgo_x86.go
  vendor/golang.org/x/sys/cpu/cpu_linux_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_other_x86.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/cpu/syscall_darwin_x86_gc.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: approved, lgtm

#1061 :robot: Triggering CI on branch 'release-next' after syncing to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1063 :robot: Triggering CI on branch 'release-next' after syncing to upstream/main
  ci
Labels: kind/sync-fork-to-upstream
