Repository openshift-knative/serving, pull requests merged in 2025-04, with the labels that each got.

#1304 [release-v1.16] Update github.com/golang-jwt/jwt/v4 to v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm

#1305 [release-v1.17] Update github.com/golang-jwt/jwt/v4 to v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm

#1339 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm

#1375 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved

#1358 [release-v1.16] Update Konflux configurations
  .tekton/kn-serving-activator-116-pull-request.yaml
  .tekton/kn-serving-activator-116-push.yaml
  .tekton/kn-serving-autoscaler-116-pull-request.yaml
  .tekton/kn-serving-autoscaler-116-push.yaml
  .tekton/kn-serving-autoscaler-hpa-116-pull-request.yaml
  .tekton/kn-serving-autoscaler-hpa-116-push.yaml
  .tekton/kn-serving-cleanup-116-pull-request.yaml
  .tekton/kn-serving-cleanup-116-push.yaml
  .tekton/kn-serving-controller-116-pull-request.yaml
  .tekton/kn-serving-controller-116-push.yaml
  .tekton/kn-serving-default-domain-116-pull-request.yaml
  .tekton/kn-serving-default-domain-116-push.yaml
  .tekton/kn-serving-queue-116-pull-request.yaml
  .tekton/kn-serving-queue-116-push.yaml
  .tekton/kn-serving-storage-version-migration-116-pull-request.yaml
  .tekton/kn-serving-storage-version-migration-116-push.yaml
  .tekton/kn-serving-test-autoscale-116-pull-request.yaml
  .tekton/kn-serving-test-autoscale-116-push.yaml
  .tekton/kn-serving-test-failing-116-pull-request.yaml
  .tekton/kn-serving-test-failing-116-push.yaml
  .tekton/kn-serving-test-grpc-ping-116-pull-request.yaml
  .tekton/kn-serving-test-grpc-ping-116-push.yaml
  .tekton/kn-serving-test-hellohttp2-116-pull-request.yaml
  .tekton/kn-serving-test-hellohttp2-116-push.yaml
  .tekton/kn-serving-test-hellovolume-116-pull-request.yaml
  .tekton/kn-serving-test-hellovolume-116-push.yaml
  .tekton/kn-serving-test-helloworld-116-pull-request.yaml
  .tekton/kn-serving-test-helloworld-116-push.yaml
  .tekton/kn-serving-test-httpproxy-116-pull-request.yaml
  .tekton/kn-serving-test-httpproxy-116-push.yaml
  .tekton/kn-serving-test-pizzaplanetv1-116-pull-request.yaml
  .tekton/kn-serving-test-pizzaplanetv1-116-push.yaml
  .tekton/kn-serving-test-pizzaplanetv2-116-pull-request.yaml
  .tekton/kn-serving-test-pizzaplanetv2-116-push.yaml
  .tekton/kn-serving-test-readiness-116-pull-request.yaml
  .tekton/kn-serving-test-readiness-116-push.yaml
  .tekton/kn-serving-test-revisionfailure-116-pull-request.yaml
  .tekton/kn-serving-test-revisionfailure-116-push.yaml
  .tekton/kn-serving-test-runtime-116-pull-request.yaml
  .tekton/kn-serving-test-runtime-116-push.yaml
  .tekton/kn-serving-test-servingcontainer-116-pull-request.yaml
  .tekton/kn-serving-test-servingcontainer-116-push.yaml
  .tekton/kn-serving-test-sidecarcontainer-116-pull-request.yaml
  .tekton/kn-serving-test-sidecarcontainer-116-push.yaml
  .tekton/kn-serving-test-singlethreaded-116-pull-request.yaml
  .tekton/kn-serving-test-singlethreaded-116-push.yaml
  .tekton/kn-serving-test-slowstart-116-pull-request.yaml
  .tekton/kn-serving-test-slowstart-116-push.yaml
  .tekton/kn-serving-test-timeout-116-pull-request.yaml
  .tekton/kn-serving-test-timeout-116-push.yaml
  .tekton/kn-serving-test-volumes-116-pull-request.yaml
  .tekton/kn-serving-test-volumes-116-push.yaml
  .tekton/kn-serving-test-wsserver-116-pull-request.yaml
  .tekton/kn-serving-test-wsserver-116-push.yaml
  .tekton/kn-serving-webhook-116-pull-request.yaml
  .tekton/kn-serving-webhook-116-push.yaml
Labels: lgtm

#1434 Update OWNERS
  OWNERS
Labels: approved

#1435 Fix script to create new release
  openshift/release/create-release-branch.sh
Labels: approved, lgtm

#1284 [release-v1.17] Update Konflux configurations
  .tekton/docker-build.yaml
  .tekton/kn-serving-activator-117-pull-request.yaml
  .tekton/kn-serving-activator-117-push.yaml
  .tekton/kn-serving-autoscaler-117-pull-request.yaml
  .tekton/kn-serving-autoscaler-117-push.yaml
  .tekton/kn-serving-autoscaler-hpa-117-pull-request.yaml
  .tekton/kn-serving-autoscaler-hpa-117-push.yaml
  .tekton/kn-serving-cleanup-117-pull-request.yaml
  .tekton/kn-serving-cleanup-117-push.yaml
  .tekton/kn-serving-controller-117-pull-request.yaml
  .tekton/kn-serving-controller-117-push.yaml
  .tekton/kn-serving-default-domain-117-pull-request.yaml
  .tekton/kn-serving-default-domain-117-push.yaml
  .tekton/kn-serving-queue-117-pull-request.yaml
  .tekton/kn-serving-queue-117-push.yaml
  .tekton/kn-serving-storage-version-migration-117-pull-request.yaml
  .tekton/kn-serving-storage-version-migration-117-push.yaml
  .tekton/kn-serving-test-autoscale-117-pull-request.yaml
  .tekton/kn-serving-test-autoscale-117-push.yaml
  .tekton/kn-serving-test-failing-117-pull-request.yaml
  .tekton/kn-serving-test-failing-117-push.yaml
  .tekton/kn-serving-test-grpc-ping-117-pull-request.yaml
  .tekton/kn-serving-test-grpc-ping-117-push.yaml
  .tekton/kn-serving-test-hellohttp2-117-pull-request.yaml
  .tekton/kn-serving-test-hellohttp2-117-push.yaml
  .tekton/kn-serving-test-hellovolume-117-pull-request.yaml
  .tekton/kn-serving-test-hellovolume-117-push.yaml
  .tekton/kn-serving-test-helloworld-117-pull-request.yaml
  .tekton/kn-serving-test-helloworld-117-push.yaml
  .tekton/kn-serving-test-httpproxy-117-pull-request.yaml
  .tekton/kn-serving-test-httpproxy-117-push.yaml
  .tekton/kn-serving-test-pizzaplanetv1-117-pull-request.yaml
  .tekton/kn-serving-test-pizzaplanetv1-117-push.yaml
  .tekton/kn-serving-test-pizzaplanetv2-117-pull-request.yaml
  .tekton/kn-serving-test-pizzaplanetv2-117-push.yaml
  .tekton/kn-serving-test-readiness-117-pull-request.yaml
  .tekton/kn-serving-test-readiness-117-push.yaml
  .tekton/kn-serving-test-revisionfailure-117-pull-request.yaml
  .tekton/kn-serving-test-revisionfailure-117-push.yaml
  .tekton/kn-serving-test-runtime-117-pull-request.yaml
  .tekton/kn-serving-test-runtime-117-push.yaml
  .tekton/kn-serving-test-servingcontainer-117-pull-request.yaml
  .tekton/kn-serving-test-servingcontainer-117-push.yaml
  .tekton/kn-serving-test-sidecarcontainer-117-pull-request.yaml
  .tekton/kn-serving-test-sidecarcontainer-117-push.yaml
  .tekton/kn-serving-test-singlethreaded-117-pull-request.yaml
  .tekton/kn-serving-test-singlethreaded-117-push.yaml
  .tekton/kn-serving-test-slowstart-117-pull-request.yaml
  .tekton/kn-serving-test-slowstart-117-push.yaml
  .tekton/kn-serving-test-timeout-117-pull-request.yaml
  .tekton/kn-serving-test-timeout-117-push.yaml
  .tekton/kn-serving-test-volumes-117-pull-request.yaml
  .tekton/kn-serving-test-volumes-117-push.yaml
  .tekton/kn-serving-test-wsserver-117-pull-request.yaml
  .tekton/kn-serving-test-wsserver-117-push.yaml
  .tekton/kn-serving-webhook-117-pull-request.yaml
  .tekton/kn-serving-webhook-117-push.yaml
Labels: needs-ok-to-test

#1439 Bump Golang image to 1.24
  openshift/generate.sh
Labels: approved, lgtm
