Repository openshift-knative/serving, pull requests merged in 2025-02, with the labels that each got.

#1145 :robot: Triggering CI on branch 'release-next' after syncing to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1138 [main] Update dependabot configurations
  .github/dependabot.yml
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, needs-ok-to-test

#1153 Add update-deps.sh call to generate-release
  openshift/release/generate-release.sh
Labels: approved, lgtm

#1154 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, ok-to-test

#1146 [release-v1.15] Update Konflux configurations
  .tekton/docker-build.yaml
Labels: approved, lgtm, ok-to-test

#1136 [release-v1.16] Update Konflux configurations
  .konflux/applications/serverless-operator-136/serverless-operator-136.yaml
  .konflux/applications/serverless-operator-136/tests/ec-test.yaml
  .konflux/applications/serverless-operator-136/tests/override-snapshot-ec-test.yaml
  .tekton/docker-build.yaml
Labels: approved, lgtm, ok-to-test

#1169 [MAIN] Remove "DELETE" from the Serving validating webhook
  openshift/patches/016-remove-delete-validation-webhook.patch
Labels: approved, lgtm

#1174 Bump go version for builder image
  openshift/ci-operator/build-image/Dockerfile
  openshift/generate.sh
Labels: approved, lgtm

#1165 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test

#1171 [RELEASE-1.16] Ensure ContainerHealthy condition is set back to True (#15712)
  pkg/reconciler/autoscaling/hpa/hpa_test.go
  pkg/reconciler/revision/reconcile_resources.go
  pkg/reconciler/revision/table_test.go
  pkg/testing/functional.go
  pkg/testing/v1/revision.go
Labels: approved, lgtm

#1180 :robot: Triggering CI on branch 'release-next' after syncing to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1182 :robot: Triggering CI on branch 'release-next' after syncing to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1168 [release-v1.17] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, ok-to-test

#1211 :robot: Triggering CI on branch 'release-next' after syncing to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1210 [release-v1.15] Fix generate-release cmd
  openshift/generate.sh
  openshift/release/generate-release.sh
Labels: approved, lgtm

#1219 :robot: Triggering CI on branch 'release-next' after syncing to upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#1217 [main] Update dependabot configurations
  renovate.json
Labels: approved, lgtm, needs-ok-to-test
