Repository openshift-knative/serving, pull requests merged in 2025-01, with the labels that each got.

#1082 [RELEASE-v1.15] Update golang.org/x/net to 0.34.0
  go.mod
  go.sum
  vendor/golang.org/x/crypto/pkcs12/crypto.go
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved, lgtm

#1089 Fix midstream patches
  openshift/patches/004-grpc.patch
  openshift/patches/012-revert-app-protocol.patch
Labels: approved, lgtm

#1088 [main] Update dependabot configurations
  .github/dependabot.yml
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, ok-to-test

#1079 [release-v1.15] Add Konflux configurations
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .konflux/applications/serverless-operator-135/tests/override-snapshot-ec-test.yaml
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm, ok-to-test

#1107 Update owners add me, rm Reto
  OWNERS
Labels: approved, lgtm

#1111 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test

#1141 Bring dependabot update action to release branch
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm

#1142 Add branch trigger to gh action
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm
